
server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

keystore:
  path: ./conf/auth-server.pfx
  pass: password

spring:
  h2:
    console:
      enabled:
        false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 100
  datasource:
    url: jdbc:h2:tcp://localhost/~/auth
    driver-class-name: org.h2.Driver
    username: sa
    password: 11
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
hibernate:
  dialect: org.hibernate.dialect.H2Dialect